---
version: 3
images:
  base_image:
    name: 'rockylinux:9'
dependencies:
    ansible_core:
      package_pip: ansible-core
    ansible_runner:
      package_pip: ansible-runner
    python_interpreter:
      package_system: "python39" 
      python_path: "/usr/bin/python3.9"
    galaxy: |
      collections:
      - source: /build/src/cisco-radkit-1.8.0.tar.gz
        type: file
      - name: ansible.netcommon
      - name: cisco.ios
      - name: cisco.meraki
    python: |
      pproxy
      pyats
      genie
      requests
      azure-communication-email
      cisco-radkit-client
      cisco-radkit-service
      cisco-radkit-common
additional_build_files:
  - dest: src
    src: src
additional_build_steps:
  prepend_builder: |
    RUN $PYCMD -m pip install --upgrade pip
  prepend_final: |
    COPY _build/src /build/src
    RUN rm -rf /build